config: dynamic_tube_mpc
onboard:
  control:
  # ----- High Level Controller ----- #
    - pkg: go2_dyn_tube_mpc
      # params:
      executable: high_level_planner
      callback_groups: 
        mpc_constraint: MutuallyExclusiveCallbackGroup
        map_update: MutuallyExclusiveCallbackGroup
        a_star: MutuallyExclusiveCallbackGroup
      publishers:
        # ----- Path Publisher ----- #
        - ros_parameter: pub_ctrl_setting
          topic: /obelisk/go2/a_star_path
          history_depth: 1
          callback_group: a_star
        # ----- Vel Limit Publisher ----- #
        - ros_parameter: pub_vel_lim_setting
          topic: /obelisk/go2/dtmpc_vel_lim
          history_depth: 1
          callback_group: a_star
        # ----- NearestPoints Publisher ----- #
        - ros_parameter: pub_nearest_points_setting
          topic: /obelisk/go2/nearest_points
          history_depth: 1
          callback_group: mpc_constraint
        # ----- Path Visualization Publisher ----- #
        - ros_parameter: pub_viz_setting
          topic: /obelisk/go2/a_star_viz
          history_depth: 1
          callback_group: a_star
        # ----- Frontier Visualization Publisher ----- #
        - ros_parameter: pub_front_setting
          topic: /obelisk/go2/frontiers
          history_depth: 1
          callback_group: a_star
      subscribers:
        # ----- Estimated State Subscriber ----- #
        - ros_parameter: sub_est_setting
          topic: /obelisk/go2/est_state
          history_depth: 1
          callback_group: a_star
        # ----- Goal Pose Subscriber ----- #
        - ros_parameter: sub_goal_setting
          topic: /obelisk/go2/goal_pose
          history_depth: 1
          callback_group: a_star
        # ----- Map Subscriber ----- #
        - ros_parameter: sub_map_setting
          topic: /map
          history_depth: 1
          callback_group: map_update
        # ----- Map Update Subscriber ----- #
        - ros_parameter: sub_map_update_setting
          topic: /map_updates
          history_depth: 10
          callback_group: map_update
      timers:
        - ros_parameter: timer_ctrl_setting
          timer_period_sec: 1.0
          callback_group: a_star
        - ros_parameter: timer_nearest_pts_setting
          timer_period_sec: 0.05
          callback_group: mpc_constraint
  # ----- DTMPC ----- #
    - pkg: go2_dyn_tube_mpc
      executable: dyn_tube_mpc
      # callback_groups:
      publishers:
        # ----- MPC Control Publisher ----- #
        - ros_parameter: pub_ctrl_setting
          topic: /obelisk/go2/dtmpc_path
          history_depth: 1
          callback_group: None
        # ----- Path Visualization Publisher ----- #
        - ros_parameter: pub_viz_setting
          topic: /obelisk/go2/dtmpc_viz
          history_depth: 1
          callback_group: None
        # ----- Constraint Visualization Publisher ----- #
        - ros_parameter: pub_constraint_setting
          topic: /obelisk/go2/dtmpc_constraint
          history_depth: 1
          callback_group: None
      subscribers:
        # ----- Estimation Subscriber ----- #
        - ros_parameter: sub_est_setting
          topic: /obelisk/go2/est_state
          history_depth: 1
          callback_group: None
        # ----- Astar Plan Subscriber ----- #
        - ros_parameter: sub_plan_setting
          topic: /obelisk/go2/a_star_path
          history_depth: 1
          callback_group: None
        # ----- Velocity Limit Subscriber ----- #
        - ros_parameter: sub_vel_lim_setting
          topic: /obelisk/go2/dtmpc_vel_lim
          history_depth: 1
          callback_group: None
        # ----- Constraint (Map) Subscriber ----- #
        - ros_parameter: sub_nearest_points_setting
          topic: /obelisk/go2/nearest_points
          history_depth: 1
          callback_group: None
        # ----- Constraint (Scan) Subscriber ----- #
        - ros_parameter: sub_scan_setting
          topic: /scan
          history_depth: 1
          callback_group: None
      timers:
        - ros_parameter: timer_ctrl_setting
          timer_period_sec: 0.05
          callback_group: None
  # ----- Tracking Controller ----- #
    - pkg: go2_dyn_tube_mpc
      executable: trajectory_tracker
      # callback_groups:
      publishers:
        # ----- Control Publisher ----- #
        - ros_parameter: pub_ctrl_setting
          topic: /obelisk/go2/vel_ctrl
          history_depth: 10
          callback_group: None
      subscribers:
        # ----- Path Subscriber ----- #
        - ros_parameter: sub_est_setting
          topic: /obelisk/go2/dtmpc_path
          history_depth: 10
          callback_group: None
      timers:
        - ros_parameter: timer_ctrl_setting
          timer_period_sec: 0.02
          callback_group: None
  # ----- Low Level Controller ----- #
    - pkg: go2_rl_vel_tracking
      params:
        policy_path: "/home/wcompton/IsaacLab/logs/rsl_rl/unitree_go2_flat/2025-02-09_17-46-38/exported/policy.pt"
        action_scale: 0.25
      executable: vel_tracking_controller
      # callback_groups:
      publishers:
        # ----- Control Publisher ----- #
        - ros_parameter: pub_ctrl_setting
          topic: /obelisk/go2/ctrl
          history_depth: 10
          callback_group: None
      subscribers:
        # ----- Estimation Subscriber ----- #
        - ros_parameter: sub_est_setting
          topic: /obelisk/go2/est_state
          history_depth: 10
          callback_group: None
        # ----- Joystick subscriber ----- #
        - ros_parameter: sub_vel_cmd_setting
          topic: /obelisk/go2/vel_ctrl
          history_depth: 10
          callback_group: None
      timers:
        - ros_parameter: timer_ctrl_setting
          timer_period_sec: 0.02
          callback_group: None
  # ----- High Level/Execution FSM Controller ----- #
    - pkg: obelisk_unitree_cpp
      executable: obelisk_unitree_joystick
      params:
        send_joystick: False
      # callback_groups:
      publishers:
      # ----- Execution FSM ----- #
        - ros_parameter: pub_exec_fsm_setting
          topic: /obelisk/go2/exec_fsm
          history_depth: 10
          callback_group: None
      # ----- High Level Control ----- #
        - ros_parameter: pub_ctrl_setting
          topic: /obelisk/go2/vel_ctrl
          history_depth: 10
          callback_group: None
      subscribers:
      # ----- Joystick subscriber ----- #
        - ros_parameter: sub_est_setting
          topic: /obelisk/go2/joy
      timers:
        - ros_parameter: timer_ctrl_setting
          timer_period_sec: 100  # Control callback is not being used
          callback_group: None
  estimation:
    - pkg: obelisk_unitree_cpp
      executable: unitree_go2_estimator
      # callback_groups:
      publishers:
        - ros_parameter: pub_est_setting
          topic: /obelisk/go2/est_state
          msg_type: EstimatedState
          history_depth: 10
          callback_group: None
      subscribers:
        - ros_parameter: sub_sensor_setting
          topic: /obelisk/go2/joint_encoders
          msg_type: ObkJointEncoders
          history_depth: 10
          callback_group: None
        - ros_parameter: sub_imu_setting
          topic: /obelisk/go2/torso_imu
          msg_type: ObkIMU
          history_depth: 10
          callback_group: None
      timers:
        - ros_parameter: timer_est_setting
          timer_period_sec: 0.001
          callback_group: None
  # sensing:
  robot:
    # === simulation ===
    - is_simulated: True
      pkg: obelisk_unitree_cpp
      executable: obelisk_unitree_sim
      params:
        ic_keyframe: standing_isaac
    # === hardware ===
    # - is_simulated: False
    #   pkg: obelisk_unitree_cpp
    #   executable: obelisk_unitree_go2_hardware
    #   params:
    #     network_interface_name: enx001cc24ce09a
    #     default_kp: [
    #                 25., 25., 25.,    # FR
    #                 25., 25., 25.,    # FL
    #                 25., 25., 25.,    # RR
    #                 25., 25., 25.,    # RL
    #                 ]
    #     default_kd: [
    #                 0.5, 0.5, 0.5,    # FR
    #                 0.5, 0.5, 0.5,    # FL
    #                 0.5, 0.5, 0.5,    # RR
    #                 0.5, 0.5, 0.5,    # RL
    #     ]
    # ==================
      # callback_groups:
      publishers:
      # ----- Joints ----- #
        - ros_parameter: pub_sensor_setting
          topic: /obelisk/go2/joint_encoders
          history_depth: 1
      # ----- IMU ----- #
        - ros_parameter: pub_imu_setting
          topic: /obelisk/go2/torso_imu
          history_depth: 1
      # ----- Odom ----- #
        - ros_parameter: pub_odom_setting
          topic: /obelisk/go2/odom
          history_depth: 1
      subscribers:
      # ----- Control ----- #
        - ros_parameter: sub_ctrl_setting
          topic: /obelisk/go2/ctrl
          history_depth: 1
          callback_group: None
      # ----- Execution FSM ----- #
        - ros_parameter: sub_fsm_setting
          topic: /obelisk/go2/exec_fsm
          history_depth: 1
          callback_group: None
      # ----- High Level Control ----- #
        - ros_parameter: sub_high_level_ctrl_setting
          topic: /obelisk/go2/high_level_ctrl
          history_depth: 1
          callback_group: None
      sim:
        - ros_parameter: mujoco_setting
          n_u: 16
          time_step: 0.002
          num_steps_per_viz: 5
          robot_pkg: go2_rl_description
          model_xml_path: go2_rl_scene.xml
          sensor_settings:
          - topic: /obelisk/go2/joint_encoders
            dt: 0.002
            msg_type: ObkJointEncoders
            sensor_names:
            # ---------- Joint Positions ---------- #
              FR_hip_joint_pos_sensor: jointpos
              FR_thigh_joint_pos_sensor: jointpos
              FR_calf_joint_pos_sensor: jointpos

              FL_hip_joint_pos_sensor: jointpos
              FL_thigh_joint_pos_sensor: jointpos
              FL_calf_joint_pos_sensor: jointpos

              RR_hip_joint_pos_sensor: jointpos
              RR_thigh_joint_pos_sensor: jointpos
              RR_calf_joint_pos_sensor: jointpos

              RL_hip_joint_pos_sensor: jointpos
              RL_thigh_joint_pos_sensor: jointpos
              RL_calf_joint_pos_sensor: jointpos
            # ---------- Joint Velocities ---------- #
              FR_hip_joint_vel_sensor: jointvel
              FR_thigh_joint_vel_sensor: jointvel
              FR_calf_joint_vel_sensor: jointvel

              FL_hip_joint_vel_sensor: jointvel
              FL_thigh_joint_vel_sensor: jointvel
              FL_calf_joint_vel_sensor: jointvel

              RR_hip_joint_vel_sensor: jointvel
              RR_thigh_joint_vel_sensor: jointvel
              RR_calf_joint_vel_sensor: jointvel

              RL_hip_joint_vel_sensor: jointvel
              RL_thigh_joint_vel_sensor: jointvel
              RL_calf_joint_vel_sensor: jointvel
          # ---------- Torso IMU ---------- #
          - topic: /obelisk/go2/torso_imu
            dt: 0.001
            msg_type: ObkImu
            sensor_names:
              imu_acc_sensor: accelerometer
              imu_gyro_sensor: gyro
              imu_quat_sensor: framequat
          # ---------- Torso IMU ---------- #
          - topic: /obelisk/go2/mocap
            dt: 0.001
            msg_type: ObkFramePose
            sensor_names:
              base_mocap_pos_sensor: framepos
              base_mocap_quat_sensor: framequat
      timers:
        - ros_parameter: timer_sensor_setting
          timer_period_sec: 0.01
          callback_group: None
  viz:
    on: True
    viz_tool: foxglove
    viz_nodes:
      - pkg: obelisk_viz_cpp
        executable: default_robot_viz
        robot_pkg: go2_rl_description
        urdf: go2.urdf
        robot_topic: robot_description
        subscribers:
          - ros_parameter: sub_viz_est_setting
            topic: /obelisk/go2/est_state
            history_depth: 10
            callback_group: None
            non_obelisk: False
        publishers:
          - ros_parameter: pub_viz_joint_setting
            topic: joint_states
            history_depth: 10
            callback_group: None
        timers:
          - ros_parameter: timer_viz_joint_setting
            timer_period_sec: 0.01
            callback_group: None
  # joystick:
  #   on: True
  #   pub_topic: /obelisk/go2/joy
  #   sub_topic: /obelisk/go2/joy_feedback
